// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uobkyqmbhxqyzjjucgpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYmt5cW1iaHhxeXpqanVjZ3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTMxNzYsImV4cCI6MjA3MTcyOTE3Nn0.xNPB9j2EnwB-uJT0vfHHXn0-TTHKhsrbMiZpT-rwybQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});